# Introduccion a Julia

Para la implementación de los ejercicios prácticos, existen varias opciones en cuanto a lenguaje de programación. Entre las muchas opciones disponibles, se han considerado tres posibilidades:

* **Matlab**. Es un lenguaje científico con muchos años de experiencia, por lo que tiene la ventaja de contar con una gran cantidad de módulos (llamados Toolboxes) para casi cualquier operación que se desee realizar, junto con una excelente documentación. Esto lo convierte en un lenguaje muy adecuado para iniciarse y aprender. Sin embargo, su principal desventaja es que es necesario adquirir una licencia para utilizarlo. Este requisito ha hecho que muchas empresas no opten por esta opción, por lo que en la práctica no es tan utilizado como Python en el ámbito empresarial.

* **Python**. Sin duda es el más utilizado. Es un lenguaje moderno, sencillo, con una gran cantidad de módulos y abundante documentación, aunque sin llegar al número o calidad de Matlab. Es gratuito y de código abierto, y de propósito general, lo que lo ha convertido en uno de los lenguajes más usados en el mundo empresarial hoy en día. Además, una de las primeras librerías de Deep Learning, llamada TensorFlow, fue desarrollada por Google para este lenguaje, lo que ha aumentado drásticamente la comunidad de desarrolladores de aplicaciones de aprendizaje automático en este lenguaje. Además, bibliotecas como Scikit-Learn también permiten el uso de otras técnicas de aprendizaje automático como árboles de decisión o máquinas de soporte vectorial. El mayor problema de este lenguaje es que no es un lenguaje científico sino de propósito general, y la programación vectorial no está soportada de forma nativa, sino a través de la librería numpy, lo que conlleva una considerable pérdida de rendimiento.

* **Julia**. Es un lenguaje emergente, de vida muy corta y completamente científico, desarrollado en el Instituto Tecnológico de Massachusetts (MIT). Su primera versión estable es de hace solo unos pocos años, y actualmente se encuentra en pleno desarrollo. Por esta razón, no cuenta con el mismo número de módulos que Matlab o Python, aunque el número de módulos crece rápidamente, ya que el lenguaje es gratuito y de código abierto. Este lenguaje ha sido desarrollado como un punto intermedio entre Matlab, como lenguaje científico, y Python, como lenguaje sencillo y de código abierto, con una velocidad de ejecución superior a ambos. Sus principales inconvenientes son que la comunidad de desarrolladores no es tan grande como la de Python, y el número de módulos no es tan amplio como el de Matlab, y, dado su corto periodo de vida, aún no se ha hecho presente en el mundo empresarial.

Como se ha indicado, es un lenguaje que todavía no tiene una gran presencia a nivel empresarial. Sin embargo, esto se mitiga por tres factores importantes:

* Dado que se han adquirido habilidades en el lenguaje Python en otras asignaturas, esta asignatura brinda la oportunidad de aprender un lenguaje científico que completa los conocimientos.

* Varias de las instituciones más prestigiosas del mundo, como Berkeley, Stanford o MIT, recomiendan y enseñan esta asignatura en este lenguaje debido al control que ofrece a la hora de investigar o implementar detalles sin perder rendimiento. Esto casi garantiza que en un corto periodo de tiempo comenzará a verse a nivel empresarial.

* Aunque Python es el lenguaje más utilizado a nivel empresarial, la librería Scikit-Learn también está disponible en Julia. Por lo tanto, su aprendizaje en esta asignatura significaría que también podrían usarlo en su trabajo en una empresa en Python sin dificultad, ya que tendrían conocimientos tanto de la librería como del lenguaje.

## Instalación

La instalación de Julia es bastante sencilla, ya sea utilizando binarios precompilados o compilando desde el código fuente. Descarga e instala Julia siguiendo las instrucciones en [https://julialang.org/downloads/].

> ⚠️ **Usuarios de Mac más antiguos**: La instalación de Julia puede ser problemática debido a compiladores obsoletos. En caso de errores durante la instalación, podría valer la pena intentar instalarlo a través de [MacPorts](https://ports.macports.org/port/julia/). Tras la [instalación de MacPorts](https://www.macports.org/install.php/), Julia se puede instalar con `sudo port install julia`.

También podría ser útil instalar Jupyter en un entorno local para realizar algunas pruebas. Esto se puede hacer ejecutando el siguiente comando, si aún no lo tienes instalado.


Para ejecutarse en la terminal si es necesario, antes de ejecutar cualquier código aquí:
```bash
        pip install notebook
```

Después de esa instalación, puedes proceder a instalar el kernel de Julia para Jupyter Notebook. Simplemente abre una terminal y escribe `julia`. Deberías ver el siguiente entorno:

![Imagen de inicio de Julia en la terminal](./img/JuliaTerminal.png "Terminal de Julia")

Para añadir soporte para notebooks, debes ejecutar las siguientes líneas, las cuales cubriremos con más detalle en las siguientes secciones.

```julia
    using Pkg
    Pkg.add("IJulia")
    
```

Estas líneas están cargando el paquete `Pkg`, que se utiliza para gestionar paquetes en Julia, y estamos añadiendo el paquete `IJulia`. Ahora puedes ejecutar comandos y crear un notebook en Julia dentro de Jupyter Notebooks. El siguiente paso es ejecutar el comando:
```bash
    jupyter notebook

Después de eso, puedes acceder a la dirección URL y crear nuevos notebooks en Python y Julia, o en ambos.

## Sintaxis básica en Julia

Esta sección mostrará algunas operaciones típicas con un doble objetivo: primero, servir como una referencia rápida (cheatsheet), y segundo, asegurar que la configuración previa está funcionando correctamente. Muchos de los ejemplos están basados en este [tutorial](https://learnxinyminutes.com/docs/julia/), que puede ser utilizado como referencia adicional.


### Tipos de números

En Julia, hay varios tipos de números. Aunque durante la primera práctica profundizaremos en esta cuestión, aquí hay algunos ejemplos de diferentes definiciones.


In [1]:
typeof(2)

Int64

In [2]:
typeof(4.0)

Float64

In [3]:
typeof(1 + 1im)

Complex{Int64}

In [4]:
typeof(2 // 3)

Rational{Int64}

In [5]:
supertype(AbstractFloat)

Real

In [6]:
supertype(Real)

Number

In [7]:
supertype(Number)

Any

### Operadores Booleanos

Ten en cuenta que la negación se realiza con `!`.

In [8]:
(1==1) & !(1!=1)

true

### Strings

In [9]:
typeof("This is a string")

String

In [10]:
typeof('a') != typeof("a") # the single quote is only for caracters

true

In [11]:
using Printf
Printf.@printf "%d is less than %f" 4.5 5.3

4 is less than 5.300000

In [12]:
println("This is in Julia - $(VERSION)")

This is in Julia - 1.10.0


### Variable

Los nombres de las variables deben comenzar con una letra, pero después de eso, puedes usar letras, dígitos, guiones bajos y signos de exclamación.


In [13]:
xMarksTheSpot2Dig! = 1

1

In [14]:
a = Int64[]

Int64[]

In [15]:
push!(a, 1)

1-element Vector{Int64}:
 1

In [16]:
push!(a, 2)

2-element Vector{Int64}:
 1
 2

In [17]:
b = [3, 4, 5]

3-element Vector{Int64}:
 3
 4
 5

In [18]:
b[1]

3

In [19]:
b[end]

5

In [20]:
append!(a, b)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [21]:
pop!(a)

5

In [22]:
a[2:3]

2-element Vector{Int64}:
 2
 3

In [23]:
4 in a

true

In [24]:
length(a)

4

### Tuplas

In [25]:
a = (1, 5, 3)
typeof(a)

Tuple{Int64, Int64, Int64}

In [26]:
a[2]

5

In [27]:
a, b, c = (1, 2, 3)

(1, 2, 3)

In [28]:
println(" First element is $(a), Second is $(b), and last is $(c)")

 First element is 1, Second is 2, and last is 3


In [29]:
n = (x=1, y=2, z=3) # use keyword assignments in a tuple to create a NamedTuple

(x = 1, y = 2, z = 3)

In [30]:
println(" First element is $(n.x), Second is $(n.y), and last is $(n.z)")

 First element is 1, Second is 2, and last is 3


### Diccionarios

In [31]:
d = Dict("one"=>1, "two"=>2, "three"=>3)

Dict{String, Int64} with 3 entries:
  "two"   => 2
  "one"   => 1
  "three" => 3

In [32]:
d["one"]

1

In [33]:
keys(d)

KeySet for a Dict{String, Int64} with 3 entries. Keys:
  "two"
  "one"
  "three"

In [34]:
values(d)

ValueIterator for a Dict{String, Int64} with 3 entries. Values:
  2
  1
  3

In [35]:
haskey(d, "one")

true

### Control de Flujo

In [38]:
condition_var = 10

# if-then=else
# Indentation is not meaningful in Julia.

if condition_var > 10
    println("If branch is mandatory")
elseif condition_var < 10    
    println("Elseif branch is optional")
else                    
    println("The else branch os also optional")
end

The else branch os also optional


In [39]:
# The for loop can work on iterables
for animal in ["dog", "cat", "mouse"]
    println("$animal is a mammal")
    # You can use $ to interpolate variables or expression into strings
end

dog is a mammal
cat is a mammal
mouse is a mammal


In [40]:
for (k,v) in Dict("dog"=>"mammal","cat"=>"mammal","mouse"=>"mammal")
    println("$k is a $v")
end

mouse is a mammal
cat is a mammal
dog is a mammal


In [41]:
# The while loop
x = 0
while x < 4
    global x # be aware that the variable which is changed is the global one
    println(x)
    x += 1  # Shorthand for x = x + 1
end

0
1
2
3


### Funciones

In [42]:
# You can define a function with or without defatult values
function defaults(a, b, x=5, y=6)
    return "$a $b and $x $y"
end

defaults (generic function with 3 methods)

In [ ]:
defaults('h', 'g')  # => "h g and j 6"

"h g and 5 6"

In [45]:
try
    defaults('h')  # => ERROR: MethodError: no method matching defaults(::Char)
catch e
    println(e)
end

MethodError(defaults, ('h',), 0x0000000000007b02)


In [46]:
function all_the_args(normalArg, optionalPositionalArg=2; keywordArg="foo")
    println("normal arg: $normalArg")
    println("optional arg: $optionalPositionalArg")
    println("keyword arg: $keywordArg")
end

all_the_args("normal")

normal arg: normal
optional arg: 2
keyword arg: foo


In [47]:
# Lambda expressions
(x -> x+1)(3)

4

In [48]:
# Julia has first class functions
function create_adder(x)
    adder = function (y)
        return x + y
    end
    return adder
end

create_adder (generic function with 1 method)

In [49]:
# This function is identical to create_adder implementation above.
function create_adder(x)
    y -> x + y
end

create_adder (generic function with 1 method)

In [50]:
# You can also name the internal function, if you want
function create_adder(x)
    function adder(y)
        x + y
    end
    adder
end

create_adder (generic function with 1 method)

In [51]:
f = create_adder(10)
map(f, [1,2,3])

3-element Vector{Int64}:
 11
 12
 13

In [52]:
filter(x -> x > 5, [3, 4, 5, 6, 7])

2-element Vector{Int64}:
 6
 7

In [53]:
[f(i) for i in [1, 2, 3]]

3-element Vector{Int64}:
 11
 12
 13

### Typos compuestos
Julia soporta la definición de nuevos tipos en una jerarquía que permite la herencia de métodos y propiedades. También permitirá el despacho múltiple.


In [54]:
abstract type Cat end # just a name and point in the type hierarchy
subtypes(Cat)

Any[]

In [55]:
# <: is the subtyping operator
struct Lion <: Cat # Lion is a subtype of Cat
    mane_color
    roar::String
end

struct Panther <: Cat # Panther is also a subtype of Cat
  eye_color
  Panther() = new("green")
  # Panthers will only have this constructor, and no default constructor.
end

# Also it is not required to inheritance anything
struct Tiger
  taillength::Float64
  coatcolor # not including a type annotation is the same as `::Any`
end

subtypes(Cat)

2-element Vector{Any}:
 Lion
 Panther

In [56]:
function voice(animal::Lion)
  animal.roar # access type properties using dot notation
end

function voice(animal::Panther)
  "grrr"
end

function voice(animal::Tiger)
  "rawwwr"
end

voice (generic function with 3 methods)

In [57]:
println("The Tiger says $(voice(Tiger(3.5,"orange")))")
println("The Lion says $(voice(Lion("brown","ROAAAR")))")
println("The Lion says $(voice(Panther()))")

The Tiger says rawwwr
The Lion says ROAAAR
The Lion says grrr


### Código Nativo

In [58]:
Add(x, y) = x + y

Add (generic function with 1 method)

In [59]:
Add(4,5)

9

In [60]:
code_native(Add, (Int32,Int32), syntax = :intel)

	.text
	.file	"Add"
	.globl	julia_Add_2152                  # -- Begin function julia_Add_2152
	.p2align	4, 0x90
	.type	julia_Add_2152,@function
julia_Add_2152:                         # @julia_Add_2152
; ┌ @ c:\Users\Alberto S\Desktop\GIA_MAAA1\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y131sZmlsZQ==.jl:1 within `Add`
	.cfi_startproc
# %bb.0:                                # %top
	push	rbp
	.cfi_def_cfa_offset 16
	.cfi_offset rbp, -16
	mov	rbp, rsp
	.cfi_def_cfa_register rbp
                                        # kill: def $edx killed $edx def $rdx
                                        # kill: def $ecx killed $ecx def $rcx
; │┌ @ int.jl:87 within `+`
	lea	eax, [rcx + rdx]
; │└
	pop	rbp
	ret
.Lfunc_end0:
	.size	julia_Add_2152, .Lfunc_end0-julia_Add_2152
	.cfi_endproc
; └
                                        # -- End function
	.section	".note.GNU-stack","",@progbits


In [4]:
code_native(Add, (Float32,Float32), syntax = :intel)

	.text
	.file	"Add"
	.globl	julia_Add_826                   # -- Begin function julia_Add_826
	.p2align	4, 0x90
	.type	julia_Add_826,@function
julia_Add_826:                          # @julia_Add_826
; ┌ @ In[1]:1 within `Add`
# %bb.0:                                # %top
	push	rbp
	mov	rbp, rsp
; │┌ @ float.jl:409 within `+`
	vaddss	xmm0, xmm0, xmm1
; │└
	pop	rbp
	ret
.Lfunc_end0:
	.size	julia_Add_826, .Lfunc_end0-julia_Add_826
; └
                                        # -- End function
	.section	".note.GNU-stack","",@progbits


In [5]:
code_llvm(Add, (Int32,Int32))

;  @ In[1]:1 within `Add`
define i32 @julia_Add_858(i32 signext %0, i32 signext %1) #0 {
top:
; ┌ @ int.jl:87 within `+`
   %2 = add i32 %1, %0
; └
  ret i32 %2
}
